# Hypothesis Testing

## Is the average total_price of all pizza sales different from $15.

In [1]:
'''
1. Define alpha value (0.05) -> risk limit
2. Define Average Value / Average value column
3. Testing function
4. Define Null Hypothesis and Alternate Hypotheisis
5. Compare Alpha Value and P-Value for decision and conclusion.
'''

'\n1. Define alpha value (0.05) -> risk limit\n2. Define Average Value / Average value column\n3. Testing function\n4. Define Null Hypothesis and Alternate Hypotheisis\n5. Compare Alpha Value and P-Value for decision and conclusion.\n'

In [2]:
import pandas as pd
from scipy import stats

In [3]:
df = pd.read_csv('D:/Broadway/Data Science - 2/pizza_sales.csv')
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

## One-Sample T-Test

In [4]:
# Alpha value
alpha = 0.05
sample = 15 # sample data
total_price = df['total_price'] # Population data

In [5]:
# testing one-sample t-test
t_statistics, pvalue = stats.ttest_1samp(total_price, popmean=sample)

In [6]:
print(f'Ho: Total Average Price of Pizza Sales is equals to ${sample}.')
print(f'Ha: Total Average Price of Pizza Sales is not equals to ${sample}.')
print(f'Average Pizza Sales according to Data: ${total_price.mean():.2f}.')
print(f'Statistics: {t_statistics:.2f}')
print(f'Probability Value (P-Value): {pvalue}')

Ho: Total Average Price of Pizza Sales is equals to $15.
Ha: Total Average Price of Pizza Sales is not equals to $15.
Average Pizza Sales according to Data: $16.82.
Statistics: 90.51
Probability Value (P-Value): 0.0

In [7]:
if pvalue > alpha:
    print(f'Decision: Failed to reject null hypotheis.\nConclusion: Total Average Price of Pizza Sales is equals to ${sample}.')
else:
    print(f'Decision: Failed to accept null hypotheis.\nConclusion: Total Average Price of Pizza Sales is not equals to ${sample}.')

Decision: Failed to accept null hypotheis.
Conclusion: Total Average Price of Pizza Sales is not equals to $15.

## Two-Sample T-Test

### Is the average unit_price of Classic pizzas vs. Chicken Pizzas equal?

In [8]:
alpha = 0.05

In [11]:
classic_price = df[df['pizza_category'] == 'Classic']['unit_price']
chicken_price = df[df['pizza_category'] == 'Chicken']['unit_price']

In [14]:
t_statistics, pvalue = stats.ttest_ind(classic_price, chicken_price, equal_var=False)

In [19]:
print('Ho: The average unit price of Classic Pizza and Chicken Pizza are Equal.')
print('Ha: The average unit price of Classic Pizza and Chicken Pizza are not Equal.')
print(f'Classic Pizza Average Price: ${classic_price.mean():,.2f}')
print(f'Chicken Pizza Average Price: ${chicken_price.mean():,.2f}')

Ho: The average unit price of Classic Pizza and Chicken Pizza are Equal.
Ha: The average unit price of Classic Pizza and Chicken Pizza are not Equal.
Classic Pizza Average Price: $14.80
Chicken Pizza Average Price: $17.71

In [18]:
if pvalue > alpha:
    print('Decision: Failed to reject Null Hypothesis.\nConclusion: The average unit price of Classic Pizza and Chicken Pizza are Equal.')
else:
    print('Decision: Failed to accept Null Hypothesis.\nConclusion: The average unit price of Classic Pizza and Chicken Pizza are not Equal.')

Decision: Failed to accept Null Hypothesis.
Conclusion: The average unit price of Classic Pizza and Chicken Pizza are not Equal.

## ANOVA Test (Analysis of Variance)

### The average total_price generated by all four pizza categories (Classic, Chicken, Supreme, and Veggie) differ significantly from one another?

In [20]:
alpha = 0.05

In [21]:
categories = df['pizza_category'].unique()
categories

array(['Classic', 'Veggie', 'Supreme', 'Chicken'], dtype=object)

In [22]:
grouped_price = []

In [25]:
for category in categories:
    pizza_price = df[df['pizza_category'] == category]['total_price']
    grouped_price.append(pizza_price)

In [29]:
t_statistics, pvalue = stats.f_oneway(*grouped_price)

In [36]:
mean_price = df.groupby('pizza_category')['total_price'].mean()

In [46]:
print("Ho: The average total_price generated by all four pizza categories does not differ significantly from one another.")
print("Ha: The average total_price generated by all four pizza categories does differ significantly from one another.")
print('-'*36)
print(mean_price.map("${:,.2f}".format).to_markdown(numalign='left', stralign='left'))
print('-'*36)

Ho: The average total_price generated by all four pizza categories does not differ significantly from one another.
Ha: The average total_price generated by all four pizza categories does differ significantly from one another.
------------------------------------
| pizza_category   | total_price   |
|:-----------------|:--------------|
| Chicken          | $18.12        |
| Classic          | $15.09        |
| Supreme          | $17.68        |
| Veggie           | $16.92        |
------------------------------------

In [48]:
if pvalue > alpha:
    print("Decision: Failed to reject Null Hypothesis.\nConclusion: The average total_price generated by all four pizza categories does not differ significantly from one another.")
else:
    print("Decision: Failed to accept Null Hypothesis.\nConclusion: The average total_price generated by all four pizza categories does differ significantly from one another.")

Decision: Failed to accept Null Hypothesis.
Conclusion: The average total_price generated by all four pizza categories does differ significantly from one another.

## Chi-Squared Test

### Is pizza category and pizza size are independent or dependent to each other.

In [50]:
alpha = 0.05

In [51]:
contingency_table = pd.crosstab(df['pizza_category'], df['pizza_size'])
contingency_table

pizza_size         L     M     S   XL  XXL
pizza_category
Chicken         4799  3811  2205    0    0
Classic         3987  4045  5975  544   28
Supreme         4477  3977  3323    0    0
Veggie          5263  3552  2634    0    0

In [ ]:
# (number_of_rows - 1)*(number_of_columns - 1)

In [54]:
t_statistis, pvalue, dof, ef = stats.chi2_contingency(contingency_table)

In [55]:
print("Ho: Pizza Category and Pizza Size are dependent to each other.")
print("Ha: Pizza Category and Pizza Size are independent to each other.")

Ho: Pizza Category and Pizza Size are dependent to each other.
Ha: Pizza Category and Pizza Size are independent to each other.

In [56]:
if pvalue > alpha:
    print("Decision: Failed to reject Null Hypothesis.\nConclusion: Pizza Category and Pizza Size are dependent to each other.")
else:
    print("Decision: Failed to accept Null Hypotheis.\nCocnlusion: Pizza Category and Pizza Size are independent to each other.")

Decision: Failed to accept Null Hypotheis.
Cocnlusion: Pizza Category and Pizza Size are independent to each other.